apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootproject-deployment
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot 
    spec:
      containers:
      - name: springboot
        image: susobhandas/springbootproject:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: springbootproject-service
spec:
  selector:
    app: springboot 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
